name: Build and Push Oracle Price Provider

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  id-token: write # requesting the OIDC JWT token

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::565802942559:role/zkusd-services-github-actions-role
          aws-region: eu-central-1

      - name: Set Docker tag
        id: set_docker_tag
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      # Configure for public ECR
      - name: Configure AWS credentials for public ECR
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::565802942559:role/zkusd-services-github-actions-role
          aws-region: us-east-1

      # Login to public ECR
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          mask-password: true

      # BUILD AND PUSH DOCKER IMAGE to both registries
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64,linux/amd64 # Build for both architectures
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/zkusd-oracle:latest
            ${{ steps.login-ecr.outputs.registry }}/zkusd-oracle:${{ steps.set_docker_tag.outputs.tag }}
            public.ecr.aws/v5p9f2o9/zkusd-oracle:latest
            public.ecr.aws/v5p9f2o9/zkusd-oracle:${{ steps.set_docker_tag.outputs.tag }}
